### PR TITLE
Gemini added #new feature

### PR DESCRIPTION
**Pull request by Piyu-Pika**
# Add Google Gemini AI Integration

## Overview
Added support for Google's Gemini AI models, enabling users to interact with Gemini's language models through the application's existing LLM interface.

## Features
- Integration with Google's Generative AI SDK
- Support for multiple Gemini models:
  - gemini-1.5-flash
  - gemini-1.5-pro
  - gemini-1.5-flash-8b
  - gemini-1.0-pro
- Streaming response support for real-time interactions
- Proper handling of system messages by combining them with the first user message
- Configurable max output tokens
- Error handling with user-friendly messages

## Implementation Details
- Added new Gemini configuration options in the config system
- Implemented message streaming using async iterators
- Added proper message history handling with role conversion (assistant → model)
- Integrated with the existing abort mechanism for message cancellation
- Added API key validation and error handling

## Configuration
Users can configure Gemini through the following settings:
- API Key: Google API key for authentication
- Model Selection: Choice between available Gemini models
- Max Tokens: Configurable through the default maxTokens setting

## Technical Notes
- Messages are properly formatted to match Gemini's expected structure
- System messages are merged with the first user message due to Gemini's message format requirements
- Streaming implementation ensures real-time response delivery
- Error handling includes specific handling of API key validation errors

## Testing Required
- Verify streaming functionality works correctly
- Test system message handling
- Confirm error scenarios are properly handled
- Validate max token limits are respected
- Check abort functionality works as expected

## Breaking Changes
None. This is an additive feature that maintains compatibility with existing LLM integrations.

### CODE REVIEW

**Comment by Piyu-Pika** [comment]
@andrewpareles . I added Gemini a widely available model by Google . The API of gemini is free of cost which can lead to the many users to use the void extension and ide . This issue is faced by me personally

**Comment by andrewpareles** [comment]
Great addition, will review in a bit.

**Comment by andrewpareles** [comment]
Reviewed and simplified, what do you think?

**Comment by andrewpareles** [comment]
I simplified this a bit. Can you run a few tests to make sure it works?

**Review by Piyu-Pika — COMMENTED** [review]
# Code Generation Testing Results

## Overview
Successfully completed comprehensive testing of code generation capabilities across multiple programming languages. The model demonstrated robust performance and reliability.

## Languages Tested
* Python
* C
* Dart
* C++

## Test Results
### Performance Metrics
- ✅ Accurate code generation
- ✅ Proper syntax maintenance
- ✅ Correct formatting
- ✅ Error-free compilation
- ✅ Successful execution

### Key Findings
* **Consistency**: Reliable performance across all tested languages
* **Syntax**: Maintained language-specific syntax rules
* **Functionality**: Generated code executed as intended
* **Integration**: Smooth implementation in development workflow

## Technical Details
- All code snippets generated with correct language conventions
- Standard library functions properly implemented
- Complex algorithms successfully generated
- Data structures correctly formatted

## Conclusion
Testing validates the model's capability to generate production-ready code across multiple programming languages. Results indicate high reliability and accuracy in code generation tasks.

**Pull request merged**
