### PR TITLE
Groq Added

### PR DESCRIPTION
**Pull request by Piyu-Pika**
# Groq Integration Update

## Overview
We have integrated Groq as a new model provider in our application, expanding our suite of AI model options. This integration allows users to leverage Groq's high-performance inference capabilities alongside existing providers like Anthropic, OpenAI, and others.

### New Configuration Options
- Added Groq API configuration in the settings:
  - API Key configuration
  - Model selection with options:
    - `mixtral-8x7b-32768`
    - `llama2-70b-4096`
    - `gemma-7b-it`

### Implementation Details
- Full streaming support for real-time responses
- Proper error handling for API issues
- Integrated with the existing message handling system
- Support for max token configuration

### 1. Superior Speed
- Groq offers significantly faster inference times compared to other providers
- Capable of processing responses up to 100x faster than traditional GPU-based systems

### 2. Consistent Performance
- Delivers reliable and stable response times
- Reduced latency variations in high-load scenarios

### 3. Cost-Effective
- Competitive pricing model
- Efficient token usage leading to potential cost savings

### 4. Model Variety
- Access to popular open-source models optimized for Groq's architecture
- Includes both large and efficient model variants

### 5. Easy Integration
- Compatible with existing message formats
- Seamless integration with the current configuration system

## Usage

To use Groq in your application:

1. Obtain a Groq API key
2. Configure the API key in settings
3. Select Groq as your provider
4. Choose your preferred model

### CODE REVIEW

**Comment by Piyu-Pika** [comment]
@andrewpareles  i dont know its showing that much changes

**Comment by Piyu-Pika** [comment]
@andrewpareles pls review it

**Comment by andrewpareles** [comment]
Can you share where you got these models? Is this an extensive list?
```
[
"mixtral-8x7b-32768",
"llama2-70b-4096",
"gemma-7b-it"
] as const
```

**Comment by Piyu-Pika** [comment]
@andrewpareles there are many modules in groq I currently added only 3 but there are more you can check them at

 https://console.groq.com/docs/models

**Comment by Piyu-Pika** [comment]
@andrewpareles Do I need to add the rest of the models too?

**Review by Piyu-Pika — COMMENTED** [review]
Pls review

**Pull request merged**
