### PR TITLE
Linux build information

### PR DESCRIPTION
**Pull request by jcommaret**
Added Linux build information, to help users build.

### CODE REVIEW

**Comment by jcommaret** [comment]
@neoapps-dev : it works, I was able to watch/run and bundle void. 
you need 8GB ;)

**Comment by andrewpareles** [comment]
I was just reading through VSCode's How to Contribute, and I saw that their RHEL steps are different: `sudo yum groupinstall "Development Tools" && sudo yum install libX11-devel.x86_64 libxkbfile-devel.x86_64 libsecret-devel krb5-devel # or .i686`

Do your instructions work on RHEL?

**Comment by andrewpareles** [comment]
Simplified, how does this look?

**Comment by jcommaret** [comment]
This is perfect !

**Pull request closed without merging**
